channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.23.1
  - psutil==5.9.1
  - scikit-learn==1.1.3
  - scipy==1.9.0
name: mlflow-env
